1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
8 CLS
10 FOR J=7 TO 2 STEP -1
20 PRINT "THERE ARE ";J;" PIES LEFT"
30 NEXT J
40 PRINT
50 PRINT "I SHALL EXPLODE"
60 FOR K=1 TO 1000
70 REM DO NOTHING
80 NEXT K
90 PRINT
100 PRINT "B A N G S P L A T T"
110 END