1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
10 PRINT "THE EIGHT TIMES TABLE"
20 FOR J=1 TO 12
30 PRINT J*8
40 NEXT J
50 END
