1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
10 PRINT "I AM SPACED",
20 PRINT "OUT"
30 PRINT "I AM SQUASHED";
40 PRINT"UP"
50 PRINT "I AM REALLY"
60 PRINT
70 PRINT "SPACED OUT"
80 END