1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
10 FOR J=1 TO 8
20 PRINT "2 PLUS 2 IS 5"
30 NEXT J
40 PRINT
50 PRINT "ONLY JOKING"
60 END