1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
10 PRINT "WHATS THE WEATHER LIKE TODAY"
20 INPUT W$
30 IF W$="RAIN" THEN PRINT "UMBRELLA TIME"
40 IF W$="SUNNY" THEN PRINT "GOOD"
50 END