1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
10 PRINT "HOW DO YOU SAY RED IN FRENCH"
20 INPUT A$
30 IF A$="ROUGE" THEN PRINT "CORRECT"
40 IF A$<>"ROUGE" THEN PRINT "NO, ROUGE"
50 END