1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
8 LET C$=""
9 LET D$=""
10 PRINT "TYPE IN SHORT MESSAGE"
20 INPUT M$
30 PRINT "NOW TYPE IN A SECRET NUMBER BETWEEN 2 AND";LEN(M$)-1
40 INPUT NUMBER
50 LET A$=RIGHTS(M$,N)
60 LET B$=LEFT$(M$,LEN(M$)-N)
70 LET M$=A$=B$
80 FOR I=1 TO LEN(M$) STEP 2
90 LET C$=C$+MID$(M$,I,1)
100 NEXT I
110 FOR J=2 TO LEN(M$) STEP 2
120 LET D$=D$+MID$(M$,J,1)
130 NEXT J
140 LET M$=C$+D$
150 PRINT "CODED MESSAGE IS"
160 PRINT M$
170 END
