1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
10 IF A=B THEN PRINT "THEY ARE EQUAL"
20 IF A>B THEN PRINT "A IS BIGGER"
30 IF A<B THEN PRINT "A IS SMALLER"
40 IF A<>B THEN PRINT "THEY ARE NOT EQUAL"
50 END
