1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
10 A$="I AM STUPID"
20 B$="ONLY FOOLS THINK"
30 C$=B$+" "+A$
40 END