1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
10 PRINT "WHAT IS YOUR NAME"
20 INPUT N$
30 PRINT "A POEM BY"
40 PRINT N$
50 PRINT "TYPE IN A WORD"
60 PRINT "THAT RHYMES WITH ME"
70 INPUT A$
80 PRINT "HERE IS THE POEM"
90 PRINT "COMPUTERS USED TO FRIGHTEN ME"
100 PRINT "BUT NOW IM HAPPY AS A"
110 PRINT A$
120 END
