1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
10 PRINT "WHAT IS YOUR NAME"
20 INPUT N$
30 PRINT "HOW OLD ARE YOU"
40 INPUT A
50 PRINT N$
60 PRINT "IS"
70 PRINT A
80 END