1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
10 INPUT "GIVE ME A NUMBER";N
20 INPUT "AND ANOTHER";M
30 PRINT N; " TIMES ";M; " IS ";N*M
40 END