1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM
10 LET A$="ROBOTS ARE GREAT"
20 LET B$="IF YOU LIKE"
30 LET C$="GREAT METAL IDIOTS"
40 PRINT A$
50 PRINT B$
60 PRINT C$
70 END
