1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
10 INPUT K$
20 IF K$="YES" THEN GOTO 100
30 IF K$="NO" THEN GOTO 200
40 STOP
100 PRINT "YOU TYPED YES"
110 STOP
200 PRINT "YOU TYPED NO"
210 END
