1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM
10 READ Q
20 READ X$
30 DATA 24, CHEESE BURGERS
40 PRINT Q
50 PRINT X$
60 END