1 REM
2 REM INTRODUCTION TO COMPUTER PROGRAMMING BASIC FOR BEGINNERS 
3 REM BY USBORNE BOOKS
4 REM https://usborne.com/browse-books/features/computer-and-coding-books/
5 REM 
10 LET B=365
20 LET D$="DAYS IN THE YEAR"
30 LET L$="EXCEPT LEAP YEAR"
40 PRINT B
50 PRINT D$
60 PRINT L$
70 END